name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BC_ACCESS_TOKEN: "${{ secrets.BC_ACCESS_TOKEN }}"
      BC_STORE_HASH: "${{ secrets.BC_STORE_HASH }}"
      BC_PRODUCT_ID: "${{ secrets.BC_PRODUCT_ID }}"
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: [ "3.4", "3.3", "3.2", "3.1", "3.0", "2.7" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
